import { EditorState, Game } from '../types';

export const Aviary: Game = {
  price: 0,
  version: 1,
  store: 'included',
  id: 'aviary',
  disableSync: true,
  name: 'Aviary',
  description: `
  *(Compare with Arboretum)*

  Arrange your birds!
  `,
  config: {
    curScenario: 'B0vIUEMQR4COSQdSQlg-jw',
    scenarios: {
      'B0vIUEMQR4COSQdSQlg-jw': {
        id: 'B0vIUEMQR4COSQdSQlg-jw',
        name: '2 Players',
        pieces: [
          'WfFGEsJ1RmW9PCC9sE5hZg',
          'd2WdMfbxQcC5SyZi60LVdg',
          'VY5L7UZlQbqvZQR_w9YU4g',
          'Lbguaf5-SLyP0AQHRQSVKA',
          'C99Y18YmQ7mRY8BLCzxAlg',
          'NPmjOHkmQ_KdZGZyp0Sfbw',
          'XPU66z0XRd2gkHhpU_CiCw',
          'Jw7I7HygTaikeoEUlXI7jQ',
          'LG6Wy9DqS4m-2tTjkCw3TA',
          'CO8IogDwS6e3gB0LxVmwBg',
          'RSa9NaNkTjOLVfg6IecjGQ',
          'CSTBddI4TjmPQ81W6lACDQ',
          'ZXLMi5KmTNGMGl9coELGEg',
          'cp1qROJ-SS6dmg3MGZ4sFw',
          'UJlil_jGSfGUi-c4ozXWUQ',
          'LflpqvFyQs-F0xTudePDzQ',
          'bwcrIVHaRwazGmNLpLcGrg',
          'VnxyUzI_TaexVCAGf2J5NA',
          'ZYFF7ynOSQKz7iHpH3ulEw',
          'NEtLnaYwSrG51mFP2_RDMA',
          'Bb62-rusTAqUcKCatYTJTg',
          'CvhgaIVRTSOgiQQKsyovag',
          'a7w_GMlYSjiS945qmBKu3Q',
          'Taun89NHTYWx4MrhFTNHWg',
          'TcB-fe0pSOevoOIYlkxHOg',
          'dq2ns-H6RW2T1GnCtAAH1Q',
          'NVfNz5M1Rwm4DJzoph3EXw',
          'cE0aksQASSe-Hu9xx8UElg',
          'D9LMt46URymy3u2MpUkcig',
          'czTeb3-HQ82h2pumsrUmwQ',
          'S6MNEIvRSHa4SIj_UbBBuA',
          'DCCHALaxQtuXySz1g2Ei_w',
          'Dg5p-ZIqSXmkilZN70qAZA',
          'EN-Xp8e1S7SxMpG0I2Gdtw',
          'L3bJqSh8TrSeNHbzBV5RlQ',
          'R9K8-SsUStyAcDoTf0zZOw',
          'JamTncHAT3-XQikKsOOQbA',
          'Rts2VxgoSZe8U7ANvwClpQ',
          'QH1P61b1QJaTA6awonK-OA',
          'OwEr5fQMQ_Ww9fDnJgpQXg',
          'abwVHMGaQ7WB-HcFws-zfQ',
          'GLpvLtt5QheP7VEQbXr4aA',
          'ImYb6l3US0W9juEKxyb5uQ',
          'JFRKi0FaQjKfyCaCAxeo9w',
          'eThroW2VTR6fGT1gbHAXzg',
          'NSjpeqKmRZe_VfDaSf4zVQ',
          'TGfGBBZvSRypjXYYRsfYtw',
          'GNdJjaObQF-212fUjZxUTw',
          'GVNAUtbMTImdwL2dGAdLFA',
          'AdgN8GAMRGeAJJ0Mvga4ig',
          'PutDM6MXRfK60Eb1udZaFw',
        ],
        players: ['WfFGEsJ1RmW9PCC9sE5hZg', 'd2WdMfbxQcC5SyZi60LVdg'],
      },
      Z9lxMc0nRrK2__4sR21sAA: {
        id: 'Z9lxMc0nRrK2__4sR21sAA',
        name: '3 Players',
        pieces: [
          'Fuc9oUtxRIuhUspc5RUs5A',
          'bqrxy_i6RQi_B75RUh6mYw',
          'Biv1A3GnT4quSV-oIy86aA',
          'Nx7k24AGSwC5ck3PQXYAeg',
          'I_ucIpgcQfGFAgzZlRiX8Q',
          'ZZO4cRORSmGNxs4RXgumsA',
          'GAiu8Nw1SfevnGdFMU2C9w',
          'ExNLvghhTPKpweSllk-AYg',
          'CyQRjUReRHO0jjATvfMfdw',
          'DOnD5sx2SrOU6tOj9BGS6w',
          'dm6G0bofREuyguCOFPgjSQ',
          'bJ7X3GmJTqKaLkXKA1Bdeg',
          'Kxe37EgkQce5txdsjYOtmw',
          'Csa5Rvt2QKWv5vlqSt6ZUg',
          'Az0m0tguQNCKHl5A3aqzbA',
          'J-gvM4gWRCO4rjnDPR_yAA',
          'LhCXGl2VSkGu_CpqegZ__g',
          'KAipdqhHRJOhPHEOQf_pMg',
          'OQ5-TB6mSsmqLNlKJogc5A',
          'FT4xYDrCSW63SbMJTOrYHw',
          'WP9ItlmZQYeDIjAD95Ai2Q',
          'VQgNjNJvRxG78DNE4ptdEg',
          'OVHxadweS5-4lB4jbiaGoQ',
          'V8GhDPXMR0KnmbH68MvsXQ',
          'aOiedPCBR-a7O6u9mFFcdA',
          'JwyZpplzT3u21DQaZACTxA',
          'PTcFBfrjREmG0SQRThSpEA',
          'bFkm5qOEQu-21JrCyfAf6g',
          'M0WHs39jR_KDYae5vUHBhg',
          'V9Bfv-55SqS-tVjXzwBW5Q',
          'Ti6u2kf8QrSHFWIN92TvBA',
          'dC69U4j4Q1-w0qjX1IZQqA',
          'Hgull7fxTXi7w87gRtx7Pg',
          'LmpZbzA7R5uq2Fv_TVgF_g',
          'eVbOUWxZS7m3uj2wbSBxbQ',
          'GHmT_1ZCRY2WlicMYRxSEw',
          'cHvQ8-KITM60Dh2LTlVKuw',
          'Sq_9PxNPQ-qX0lql18ed3w',
          'H-rmniJjTHWwKlVPH6nj0Q',
          'aiY3PCkBRnKV_1-VQ-lxpw',
          'FMLwtFArTyuQKV2sI9xmhA',
          'SNBpTjOLTrG0LZXE3fxx6g',
          'MZRUD8rrSs2sgJSqaUHixw',
          'YJa6pZbvRPSeHQOIzejhHg',
          'Hq6JvtLkRSy58rewJg-u9w',
          'dmz5Y7YnQY-CozdrQtSaig',
          'Rvc1SUG6Rk6uSIFBaSUn9g',
          'QxwBnvMhTVq9uM3nPOBgaw',
          'aIHocEpxSF-fWb7HC_qiaw',
          'Xe3_Jk0YQu-V_Lu2Hzgxow',
          'epvHVbDgRPaVJE0blEptOQ',
          'IjcSOQwjRcWwBoFVrqUfGg',
          'GArmTxlCRMaMmvGIAkfxdw',
          'Ajf-nGM8Sl-qMTmkvm7mlQ',
          'bW8fgRqkQ42-EIEpKwuClg',
          'OwaQIx5jSCK-IHFBmthimQ',
          'IJUYC2beSUyblxP7_cqi-g',
          'Am2YnUm8TCOFhao59dcsNA',
          'W4bbohprQD6E-bBZ1J1fCQ',
          'Iv5vxj6RQ7C-ieL1fxLk8g',
          'SXRP0t8-SICJ3KP_DnHo5Q',
          'FLpT9Bi6RkCVJqmfCaiqHw',
          'UV53KD3lTgKkgsZ1QoPVjA',
          'DjKYk726SSmVMEfT0yr9lg',
          'bQtGxqRCTDu3N-I_r2_Y-Q',
          'Klp5WSJLSxKWpPlN4Aktqg',
          'JBqB_7nhQT21F_tr27ZslA',
          'GTAFlzH6SOW3hasFXajJ0A',
        ],
        players: [
          'Fuc9oUtxRIuhUspc5RUs5A',
          'bqrxy_i6RQi_B75RUh6mYw',
          'GTAFlzH6SOW3hasFXajJ0A',
        ],
      },
      cFJDGljnTUirWkmMAUwNkg: {
        id: 'cFJDGljnTUirWkmMAUwNkg',
        name: '4 Players',
        pieces: [
          'OHDDgUtfQQuyFOVU4sg8UA',
          'R_DwZfPQRk6SGmwvdL3bXA',
          'J9G3J2fcS_Kr0hI2nPj9oA',
          'QSNITB23T1OrsQJxDz8Bog',
          'Zsl4h22rQNOW82KH_mSqvg',
          'ESg3gR7WTPu6FtpTVn8Q9A',
          'RNqgbWduRh6ZCVABdwr6oA',
          'dChwF4mFRpKvCh1EhspUWQ',
          'B3s-KsI9SC6IKYlKQIXIpQ',
          'GtzT3MLnSX6s0AGuokK-tA',
          'Za1-rWNYSUukRva0v1y1iA',
          'SDrx7OKqR7Kr0rXBT84Bnw',
          'LF1EPzPNRE-c2_yQUuAVaA',
          'd40JOUslTtCQGsivc5htCg',
          'AVr6pdM5Q7ykzYTrM4eEBg',
          'QYXHlxO5TDO8m6CFd_Uq6g',
          'BKKjvFckT86hstM7usKZgA',
          'JZb3BVbySSKidYwkiEUorg',
          'R0PsXv_YStewqLzDpxAEiA',
          'CGzvMRHqTYioYI6e9EVCQQ',
          'H4sO08hOQyWxAVed5APJRw',
          'SFVv2haMRSCt3_EfpoXMDw',
          'C_SrwYNPQqi_fzQdZpw7-w',
          'M_yjlaffQkC23kF7AmeB5g',
          'Daci6TvyQCu77UFWrsOgdg',
          'CMyfntViQCWCR6u4MEvaUA',
          'f0HshnR2S_m0sGUe4y_zKA',
          'GQFvDtjsRiGixBh0EgYMjA',
          'dNXe1X0PRK2LLed1dcCDCw',
          'Usf649srQDK6ye9dWxIY7Q',
          'GK2gFfHUSQCeTIGahCTu3g',
          'EknqM3SgQo-n6zlaKq0a9g',
          'IeowvM4wR3GnWi6Z8pLxmQ',
          'e8HZWRhrQqGA8lz64i7vHQ',
          'Tjz0bdYFT96PCcv1EhGSmA',
          'DoR2ZWrzTsmbQ_TnnZkW5w',
          'MGn7S82hSTC3Zr1Q16oO3A',
          'X3nIA4LMRzm35DyzlTs4yA',
          'Zqh6nCAiRTyKlr3WCYuWGg',
          'P1rqpbn5Qr-E81I-l9aCMw',
          'Eo8aDAiJR5WB_FW6B6GNSw',
          'SBpXYtegQ4qjW43N77y15g',
          'H3aDHWAHS2mo9_boe4r-2g',
          'eKHmPTRqQsyWT512AjtS5g',
          'A42FVlnjSNOBmSuKbI-Hzg',
          'Zjr0U5f2SDGZhCwfZF4_mA',
          'JqXrI876QgeJcQ7u1Rz5Bw',
          'LNt8DaxaQlqkJ-c1vOQYfQ',
          'XKFKdo8oQvCI8gJIBGoTRg',
          'bO4m98mPS4uoE0CKaQqNoA',
          'dnXgTObzR1Or_0SOZnhe6Q',
          'D0D_rXJqSSq3ZO3iuQf9-Q',
          'PMaYdbcOS3eQMWnlKWGfhg',
          'H_FZsM7AQd21oZnyqVU61g',
          'QbbJZaAgRICHPeboEEUUEw',
          'N9VRIcyBTZGd5q2v_gVoPQ',
          'Lfc_ADOrQI-Vsed_BWELTg',
          'IwaBN5jqSpGCm-K9jPvFSQ',
          'BnMm_siVQ0-qkOvFHXPDQQ',
          'YjCSmN3lQCusLwWHs341CQ',
          'N26WBNGrRbyn3vxWIUU0Kg',
          'GzqalkjETry92NlZBFPctw',
          'dwg2PrUnQ0KJNUz_FNQCGw',
          'c5T0xDW5STeSoZl6m_Cpsg',
          'WvmKTjm2Tc-hLg3PIJmQTg',
          'KCUdtt2ATXqKUpbuu9IZ_g',
          'Bf4YplqkQdyT2tjOpNVr3A',
          'IDcBa3EpSeG-vEoCHsElew',
          'FdI_Wo9aSKCpcrrMjlccDg',
          'AN7s8X7QRumirmOg9BIrFA',
          'JwNl5LvXTGSJdn4fWZ87qw',
          'OYZ74KypQf6vdwJkfJVHJw',
          'D9_DzbJaReedKu65hF5O-Q',
          'QBfBDBlhSIWpR9S9aOaB2A',
          'NFMDLBAkRYehf9hYr0tGRA',
          'H62rW6l4RBatauCDM4davA',
          'S6Rg1ZXcSxO8kBttAYjsXw',
          'GeCwYVGxTECvVVY5cpNRWA',
          'Q38sspcoQGauLP7wqT-aSw',
          'M473Pf4ST_aAyFS-5PyIrA',
          'GIXmGJhsScWODxq9bMnU8g',
          'J4iK1_hjTl67ADuMNS9L1A',
          'PVmg2nIgScq7LU6w4xNUUA',
          'C2a4BNPKRjGrUV6h-Lyrsw',
          'D2fM8-VDSHKScA7ci00Icg',
        ],
        players: [
          'OHDDgUtfQQuyFOVU4sg8UA',
          'R_DwZfPQRk6SGmwvdL3bXA',
          'C2a4BNPKRjGrUV6h-Lyrsw',
          'D2fM8-VDSHKScA7ci00Icg',
        ],
      },
    },
    pieces: {
      WfFGEsJ1RmW9PCC9sE5hZg: {
        id: 'WfFGEsJ1RmW9PCC9sE5hZg',
        type: 'player',
        name: 'Player',
        x: 54,
        y: 518,
        width: 261.904296875,
        height: 32,
        color: '#e74c3c',
        rotation: 0,
        layer: 99,
      },
      d2WdMfbxQcC5SyZi60LVdg: {
        id: 'd2WdMfbxQcC5SyZi60LVdg',
        type: 'player',
        name: 'Player',
        x: 941,
        y: 537,
        width: 261.904296875,
        height: 32,
        color: '#f1c40f',
        rotation: 0,
        layer: 99,
      },
      VY5L7UZlQbqvZQR_w9YU4g: {
        id: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 218.53465848427138,
        height: 336.83913525771146,
        type: 'deck',
        layer: 3,
        cards: [],
        name: 'Deck',
        image: 'games/aviary/deck.png',
        x: 75,
        y: 108,
        rotation: 0,
      },
      'Lbguaf5-SLyP0AQHRQSVKA': {
        id: 'Lbguaf5-SLyP0AQHRQSVKA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        faceDown: false,
        width: 532,
        height: 820,
        type: 'card',
        image: 'games/aviary/bearded_tit_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      C99Y18YmQ7mRY8BLCzxAlg: {
        id: 'C99Y18YmQ7mRY8BLCzxAlg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      NPmjOHkmQ_KdZGZyp0Sfbw: {
        id: 'NPmjOHkmQ_KdZGZyp0Sfbw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      XPU66z0XRd2gkHhpU_CiCw: {
        id: 'XPU66z0XRd2gkHhpU_CiCw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Jw7I7HygTaikeoEUlXI7jQ: {
        id: 'Jw7I7HygTaikeoEUlXI7jQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'LG6Wy9DqS4m-2tTjkCw3TA': {
        id: 'LG6Wy9DqS4m-2tTjkCw3TA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      CO8IogDwS6e3gB0LxVmwBg: {
        id: 'CO8IogDwS6e3gB0LxVmwBg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      RSa9NaNkTjOLVfg6IecjGQ: {
        id: 'RSa9NaNkTjOLVfg6IecjGQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      CSTBddI4TjmPQ81W6lACDQ: {
        id: 'CSTBddI4TjmPQ81W6lACDQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      ZXLMi5KmTNGMGl9coELGEg: {
        id: 'ZXLMi5KmTNGMGl9coELGEg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'cp1qROJ-SS6dmg3MGZ4sFw': {
        id: 'cp1qROJ-SS6dmg3MGZ4sFw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'UJlil_jGSfGUi-c4ozXWUQ': {
        id: 'UJlil_jGSfGUi-c4ozXWUQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'LflpqvFyQs-F0xTudePDzQ': {
        id: 'LflpqvFyQs-F0xTudePDzQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      bwcrIVHaRwazGmNLpLcGrg: {
        id: 'bwcrIVHaRwazGmNLpLcGrg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      VnxyUzI_TaexVCAGf2J5NA: {
        id: 'VnxyUzI_TaexVCAGf2J5NA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      ZYFF7ynOSQKz7iHpH3ulEw: {
        id: 'ZYFF7ynOSQKz7iHpH3ulEw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      NEtLnaYwSrG51mFP2_RDMA: {
        id: 'NEtLnaYwSrG51mFP2_RDMA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Bb62-rusTAqUcKCatYTJTg': {
        id: 'Bb62-rusTAqUcKCatYTJTg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      CvhgaIVRTSOgiQQKsyovag: {
        id: 'CvhgaIVRTSOgiQQKsyovag',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      a7w_GMlYSjiS945qmBKu3Q: {
        id: 'a7w_GMlYSjiS945qmBKu3Q',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Taun89NHTYWx4MrhFTNHWg: {
        id: 'Taun89NHTYWx4MrhFTNHWg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'TcB-fe0pSOevoOIYlkxHOg': {
        id: 'TcB-fe0pSOevoOIYlkxHOg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'dq2ns-H6RW2T1GnCtAAH1Q': {
        id: 'dq2ns-H6RW2T1GnCtAAH1Q',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      NVfNz5M1Rwm4DJzoph3EXw: {
        id: 'NVfNz5M1Rwm4DJzoph3EXw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'cE0aksQASSe-Hu9xx8UElg': {
        id: 'cE0aksQASSe-Hu9xx8UElg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      D9LMt46URymy3u2MpUkcig: {
        id: 'D9LMt46URymy3u2MpUkcig',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'czTeb3-HQ82h2pumsrUmwQ': {
        id: 'czTeb3-HQ82h2pumsrUmwQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      S6MNEIvRSHa4SIj_UbBBuA: {
        id: 'S6MNEIvRSHa4SIj_UbBBuA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      DCCHALaxQtuXySz1g2Ei_w: {
        id: 'DCCHALaxQtuXySz1g2Ei_w',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Dg5p-ZIqSXmkilZN70qAZA': {
        id: 'Dg5p-ZIqSXmkilZN70qAZA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'EN-Xp8e1S7SxMpG0I2Gdtw': {
        id: 'EN-Xp8e1S7SxMpG0I2Gdtw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      L3bJqSh8TrSeNHbzBV5RlQ: {
        id: 'L3bJqSh8TrSeNHbzBV5RlQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'R9K8-SsUStyAcDoTf0zZOw': {
        id: 'R9K8-SsUStyAcDoTf0zZOw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'JamTncHAT3-XQikKsOOQbA': {
        id: 'JamTncHAT3-XQikKsOOQbA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Rts2VxgoSZe8U7ANvwClpQ: {
        id: 'Rts2VxgoSZe8U7ANvwClpQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'QH1P61b1QJaTA6awonK-OA': {
        id: 'QH1P61b1QJaTA6awonK-OA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      OwEr5fQMQ_Ww9fDnJgpQXg: {
        id: 'OwEr5fQMQ_Ww9fDnJgpQXg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'abwVHMGaQ7WB-HcFws-zfQ': {
        id: 'abwVHMGaQ7WB-HcFws-zfQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GLpvLtt5QheP7VEQbXr4aA: {
        id: 'GLpvLtt5QheP7VEQbXr4aA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      ImYb6l3US0W9juEKxyb5uQ: {
        id: 'ImYb6l3US0W9juEKxyb5uQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      JFRKi0FaQjKfyCaCAxeo9w: {
        id: 'JFRKi0FaQjKfyCaCAxeo9w',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      eThroW2VTR6fGT1gbHAXzg: {
        id: 'eThroW2VTR6fGT1gbHAXzg',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      NSjpeqKmRZe_VfDaSf4zVQ: {
        id: 'NSjpeqKmRZe_VfDaSf4zVQ',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      TGfGBBZvSRypjXYYRsfYtw: {
        id: 'TGfGBBZvSRypjXYYRsfYtw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'GNdJjaObQF-212fUjZxUTw': {
        id: 'GNdJjaObQF-212fUjZxUTw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GVNAUtbMTImdwL2dGAdLFA: {
        id: 'GVNAUtbMTImdwL2dGAdLFA',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      AdgN8GAMRGeAJJ0Mvga4ig: {
        id: 'AdgN8GAMRGeAJJ0Mvga4ig',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      PutDM6MXRfK60Eb1udZaFw: {
        id: 'PutDM6MXRfK60Eb1udZaFw',
        deckId: 'VY5L7UZlQbqvZQR_w9YU4g',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Fuc9oUtxRIuhUspc5RUs5A: {
        id: 'Fuc9oUtxRIuhUspc5RUs5A',
        type: 'player',
        name: 'Player',
        x: 54,
        y: 518,
        width: 261.904296875,
        height: 32,
        color: '#e74c3c',
        rotation: 0,
        layer: 99,
      },
      bqrxy_i6RQi_B75RUh6mYw: {
        id: 'bqrxy_i6RQi_B75RUh6mYw',
        type: 'player',
        name: 'Player',
        x: 941,
        y: 537,
        width: 261.904296875,
        height: 32,
        color: '#f1c40f',
        rotation: 0,
        layer: 99,
      },
      'Biv1A3GnT4quSV-oIy86aA': {
        id: 'Biv1A3GnT4quSV-oIy86aA',
        width: 218.53465848427138,
        height: 336.83913525771146,
        type: 'deck',
        layer: 3,
        cards: [],
        name: 'Deck',
        image: 'games/aviary/deck.png',
        x: 75,
        y: 108,
        rotation: 0,
      },
      Nx7k24AGSwC5ck3PQXYAeg: {
        id: 'Nx7k24AGSwC5ck3PQXYAeg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      I_ucIpgcQfGFAgzZlRiX8Q: {
        id: 'I_ucIpgcQfGFAgzZlRiX8Q',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      ZZO4cRORSmGNxs4RXgumsA: {
        id: 'ZZO4cRORSmGNxs4RXgumsA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GAiu8Nw1SfevnGdFMU2C9w: {
        id: 'GAiu8Nw1SfevnGdFMU2C9w',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'ExNLvghhTPKpweSllk-AYg': {
        id: 'ExNLvghhTPKpweSllk-AYg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      CyQRjUReRHO0jjATvfMfdw: {
        id: 'CyQRjUReRHO0jjATvfMfdw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      DOnD5sx2SrOU6tOj9BGS6w: {
        id: 'DOnD5sx2SrOU6tOj9BGS6w',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      dm6G0bofREuyguCOFPgjSQ: {
        id: 'dm6G0bofREuyguCOFPgjSQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      bJ7X3GmJTqKaLkXKA1Bdeg: {
        id: 'bJ7X3GmJTqKaLkXKA1Bdeg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Kxe37EgkQce5txdsjYOtmw: {
        id: 'Kxe37EgkQce5txdsjYOtmw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Csa5Rvt2QKWv5vlqSt6ZUg: {
        id: 'Csa5Rvt2QKWv5vlqSt6ZUg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Az0m0tguQNCKHl5A3aqzbA: {
        id: 'Az0m0tguQNCKHl5A3aqzbA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'J-gvM4gWRCO4rjnDPR_yAA': {
        id: 'J-gvM4gWRCO4rjnDPR_yAA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      LhCXGl2VSkGu_CpqegZ__g: {
        id: 'LhCXGl2VSkGu_CpqegZ__g',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      KAipdqhHRJOhPHEOQf_pMg: {
        id: 'KAipdqhHRJOhPHEOQf_pMg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'OQ5-TB6mSsmqLNlKJogc5A': {
        id: 'OQ5-TB6mSsmqLNlKJogc5A',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      FT4xYDrCSW63SbMJTOrYHw: {
        id: 'FT4xYDrCSW63SbMJTOrYHw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      WP9ItlmZQYeDIjAD95Ai2Q: {
        id: 'WP9ItlmZQYeDIjAD95Ai2Q',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      VQgNjNJvRxG78DNE4ptdEg: {
        id: 'VQgNjNJvRxG78DNE4ptdEg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'OVHxadweS5-4lB4jbiaGoQ': {
        id: 'OVHxadweS5-4lB4jbiaGoQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      V8GhDPXMR0KnmbH68MvsXQ: {
        id: 'V8GhDPXMR0KnmbH68MvsXQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'aOiedPCBR-a7O6u9mFFcdA': {
        id: 'aOiedPCBR-a7O6u9mFFcdA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      JwyZpplzT3u21DQaZACTxA: {
        id: 'JwyZpplzT3u21DQaZACTxA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      PTcFBfrjREmG0SQRThSpEA: {
        id: 'PTcFBfrjREmG0SQRThSpEA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'bFkm5qOEQu-21JrCyfAf6g': {
        id: 'bFkm5qOEQu-21JrCyfAf6g',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      M0WHs39jR_KDYae5vUHBhg: {
        id: 'M0WHs39jR_KDYae5vUHBhg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'V9Bfv-55SqS-tVjXzwBW5Q': {
        id: 'V9Bfv-55SqS-tVjXzwBW5Q',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Ti6u2kf8QrSHFWIN92TvBA: {
        id: 'Ti6u2kf8QrSHFWIN92TvBA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'dC69U4j4Q1-w0qjX1IZQqA': {
        id: 'dC69U4j4Q1-w0qjX1IZQqA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Hgull7fxTXi7w87gRtx7Pg: {
        id: 'Hgull7fxTXi7w87gRtx7Pg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      LmpZbzA7R5uq2Fv_TVgF_g: {
        id: 'LmpZbzA7R5uq2Fv_TVgF_g',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      eVbOUWxZS7m3uj2wbSBxbQ: {
        id: 'eVbOUWxZS7m3uj2wbSBxbQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GHmT_1ZCRY2WlicMYRxSEw: {
        id: 'GHmT_1ZCRY2WlicMYRxSEw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'cHvQ8-KITM60Dh2LTlVKuw': {
        id: 'cHvQ8-KITM60Dh2LTlVKuw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Sq_9PxNPQ-qX0lql18ed3w': {
        id: 'Sq_9PxNPQ-qX0lql18ed3w',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'H-rmniJjTHWwKlVPH6nj0Q': {
        id: 'H-rmniJjTHWwKlVPH6nj0Q',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'aiY3PCkBRnKV_1-VQ-lxpw': {
        id: 'aiY3PCkBRnKV_1-VQ-lxpw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      FMLwtFArTyuQKV2sI9xmhA: {
        id: 'FMLwtFArTyuQKV2sI9xmhA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      SNBpTjOLTrG0LZXE3fxx6g: {
        id: 'SNBpTjOLTrG0LZXE3fxx6g',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      MZRUD8rrSs2sgJSqaUHixw: {
        id: 'MZRUD8rrSs2sgJSqaUHixw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      YJa6pZbvRPSeHQOIzejhHg: {
        id: 'YJa6pZbvRPSeHQOIzejhHg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Hq6JvtLkRSy58rewJg-u9w': {
        id: 'Hq6JvtLkRSy58rewJg-u9w',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'dmz5Y7YnQY-CozdrQtSaig': {
        id: 'dmz5Y7YnQY-CozdrQtSaig',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Rvc1SUG6Rk6uSIFBaSUn9g: {
        id: 'Rvc1SUG6Rk6uSIFBaSUn9g',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      QxwBnvMhTVq9uM3nPOBgaw: {
        id: 'QxwBnvMhTVq9uM3nPOBgaw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'aIHocEpxSF-fWb7HC_qiaw': {
        id: 'aIHocEpxSF-fWb7HC_qiaw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Xe3_Jk0YQu-V_Lu2Hzgxow': {
        id: 'Xe3_Jk0YQu-V_Lu2Hzgxow',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      epvHVbDgRPaVJE0blEptOQ: {
        id: 'epvHVbDgRPaVJE0blEptOQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      IjcSOQwjRcWwBoFVrqUfGg: {
        id: 'IjcSOQwjRcWwBoFVrqUfGg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GArmTxlCRMaMmvGIAkfxdw: {
        id: 'GArmTxlCRMaMmvGIAkfxdw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Ajf-nGM8Sl-qMTmkvm7mlQ': {
        id: 'Ajf-nGM8Sl-qMTmkvm7mlQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'bW8fgRqkQ42-EIEpKwuClg': {
        id: 'bW8fgRqkQ42-EIEpKwuClg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'OwaQIx5jSCK-IHFBmthimQ': {
        id: 'OwaQIx5jSCK-IHFBmthimQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'IJUYC2beSUyblxP7_cqi-g': {
        id: 'IJUYC2beSUyblxP7_cqi-g',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Am2YnUm8TCOFhao59dcsNA: {
        id: 'Am2YnUm8TCOFhao59dcsNA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'W4bbohprQD6E-bBZ1J1fCQ': {
        id: 'W4bbohprQD6E-bBZ1J1fCQ',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Iv5vxj6RQ7C-ieL1fxLk8g': {
        id: 'Iv5vxj6RQ7C-ieL1fxLk8g',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'SXRP0t8-SICJ3KP_DnHo5Q': {
        id: 'SXRP0t8-SICJ3KP_DnHo5Q',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      FLpT9Bi6RkCVJqmfCaiqHw: {
        id: 'FLpT9Bi6RkCVJqmfCaiqHw',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      UV53KD3lTgKkgsZ1QoPVjA: {
        id: 'UV53KD3lTgKkgsZ1QoPVjA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      DjKYk726SSmVMEfT0yr9lg: {
        id: 'DjKYk726SSmVMEfT0yr9lg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'bQtGxqRCTDu3N-I_r2_Y-Q': {
        id: 'bQtGxqRCTDu3N-I_r2_Y-Q',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Klp5WSJLSxKWpPlN4Aktqg: {
        id: 'Klp5WSJLSxKWpPlN4Aktqg',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      JBqB_7nhQT21F_tr27ZslA: {
        id: 'JBqB_7nhQT21F_tr27ZslA',
        deckId: 'Biv1A3GnT4quSV-oIy86aA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      OHDDgUtfQQuyFOVU4sg8UA: {
        id: 'OHDDgUtfQQuyFOVU4sg8UA',
        type: 'player',
        name: 'Player',
        x: 54,
        y: 518,
        width: 261.904296875,
        height: 32,
        color: '#e74c3c',
        rotation: 0,
        layer: 99,
      },
      R_DwZfPQRk6SGmwvdL3bXA: {
        id: 'R_DwZfPQRk6SGmwvdL3bXA',
        type: 'player',
        name: 'Player',
        x: 941,
        y: 537,
        width: 261.904296875,
        height: 32,
        color: '#f1c40f',
        rotation: 0,
        layer: 99,
      },
      J9G3J2fcS_Kr0hI2nPj9oA: {
        id: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 218.53465848427138,
        height: 336.83913525771146,
        type: 'deck',
        layer: 3,
        cards: [],
        name: 'Deck',
        image: 'games/aviary/deck.png',
        x: 75,
        y: 108,
        rotation: 0,
      },
      QSNITB23T1OrsQJxDz8Bog: {
        id: 'QSNITB23T1OrsQJxDz8Bog',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Zsl4h22rQNOW82KH_mSqvg: {
        id: 'Zsl4h22rQNOW82KH_mSqvg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      ESg3gR7WTPu6FtpTVn8Q9A: {
        id: 'ESg3gR7WTPu6FtpTVn8Q9A',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      RNqgbWduRh6ZCVABdwr6oA: {
        id: 'RNqgbWduRh6ZCVABdwr6oA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      dChwF4mFRpKvCh1EhspUWQ: {
        id: 'dChwF4mFRpKvCh1EhspUWQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'B3s-KsI9SC6IKYlKQIXIpQ': {
        id: 'B3s-KsI9SC6IKYlKQIXIpQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'GtzT3MLnSX6s0AGuokK-tA': {
        id: 'GtzT3MLnSX6s0AGuokK-tA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Za1-rWNYSUukRva0v1y1iA': {
        id: 'Za1-rWNYSUukRva0v1y1iA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/bearded_tit_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      SDrx7OKqR7Kr0rXBT84Bnw: {
        id: 'SDrx7OKqR7Kr0rXBT84Bnw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'LF1EPzPNRE-c2_yQUuAVaA': {
        id: 'LF1EPzPNRE-c2_yQUuAVaA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      d40JOUslTtCQGsivc5htCg: {
        id: 'd40JOUslTtCQGsivc5htCg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      AVr6pdM5Q7ykzYTrM4eEBg: {
        id: 'AVr6pdM5Q7ykzYTrM4eEBg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      QYXHlxO5TDO8m6CFd_Uq6g: {
        id: 'QYXHlxO5TDO8m6CFd_Uq6g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      BKKjvFckT86hstM7usKZgA: {
        id: 'BKKjvFckT86hstM7usKZgA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      JZb3BVbySSKidYwkiEUorg: {
        id: 'JZb3BVbySSKidYwkiEUorg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      R0PsXv_YStewqLzDpxAEiA: {
        id: 'R0PsXv_YStewqLzDpxAEiA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/crow_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      CGzvMRHqTYioYI6e9EVCQQ: {
        id: 'CGzvMRHqTYioYI6e9EVCQQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      H4sO08hOQyWxAVed5APJRw: {
        id: 'H4sO08hOQyWxAVed5APJRw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      SFVv2haMRSCt3_EfpoXMDw: {
        id: 'SFVv2haMRSCt3_EfpoXMDw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'C_SrwYNPQqi_fzQdZpw7-w': {
        id: 'C_SrwYNPQqi_fzQdZpw7-w',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      M_yjlaffQkC23kF7AmeB5g: {
        id: 'M_yjlaffQkC23kF7AmeB5g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Daci6TvyQCu77UFWrsOgdg: {
        id: 'Daci6TvyQCu77UFWrsOgdg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      CMyfntViQCWCR6u4MEvaUA: {
        id: 'CMyfntViQCWCR6u4MEvaUA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      f0HshnR2S_m0sGUe4y_zKA: {
        id: 'f0HshnR2S_m0sGUe4y_zKA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/falcon_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GQFvDtjsRiGixBh0EgYMjA: {
        id: 'GQFvDtjsRiGixBh0EgYMjA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      dNXe1X0PRK2LLed1dcCDCw: {
        id: 'dNXe1X0PRK2LLed1dcCDCw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Usf649srQDK6ye9dWxIY7Q: {
        id: 'Usf649srQDK6ye9dWxIY7Q',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GK2gFfHUSQCeTIGahCTu3g: {
        id: 'GK2gFfHUSQCeTIGahCTu3g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'EknqM3SgQo-n6zlaKq0a9g': {
        id: 'EknqM3SgQo-n6zlaKq0a9g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      IeowvM4wR3GnWi6Z8pLxmQ: {
        id: 'IeowvM4wR3GnWi6Z8pLxmQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      e8HZWRhrQqGA8lz64i7vHQ: {
        id: 'e8HZWRhrQqGA8lz64i7vHQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Tjz0bdYFT96PCcv1EhGSmA: {
        id: 'Tjz0bdYFT96PCcv1EhGSmA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kingfisher_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      DoR2ZWrzTsmbQ_TnnZkW5w: {
        id: 'DoR2ZWrzTsmbQ_TnnZkW5w',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      MGn7S82hSTC3Zr1Q16oO3A: {
        id: 'MGn7S82hSTC3Zr1Q16oO3A',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      X3nIA4LMRzm35DyzlTs4yA: {
        id: 'X3nIA4LMRzm35DyzlTs4yA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Zqh6nCAiRTyKlr3WCYuWGg: {
        id: 'Zqh6nCAiRTyKlr3WCYuWGg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'P1rqpbn5Qr-E81I-l9aCMw': {
        id: 'P1rqpbn5Qr-E81I-l9aCMw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Eo8aDAiJR5WB_FW6B6GNSw: {
        id: 'Eo8aDAiJR5WB_FW6B6GNSw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      SBpXYtegQ4qjW43N77y15g: {
        id: 'SBpXYtegQ4qjW43N77y15g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'H3aDHWAHS2mo9_boe4r-2g': {
        id: 'H3aDHWAHS2mo9_boe4r-2g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/kite_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      eKHmPTRqQsyWT512AjtS5g: {
        id: 'eKHmPTRqQsyWT512AjtS5g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'A42FVlnjSNOBmSuKbI-Hzg': {
        id: 'A42FVlnjSNOBmSuKbI-Hzg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Zjr0U5f2SDGZhCwfZF4_mA: {
        id: 'Zjr0U5f2SDGZhCwfZF4_mA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      JqXrI876QgeJcQ7u1Rz5Bw: {
        id: 'JqXrI876QgeJcQ7u1Rz5Bw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'LNt8DaxaQlqkJ-c1vOQYfQ': {
        id: 'LNt8DaxaQlqkJ-c1vOQYfQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      XKFKdo8oQvCI8gJIBGoTRg: {
        id: 'XKFKdo8oQvCI8gJIBGoTRg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      bO4m98mPS4uoE0CKaQqNoA: {
        id: 'bO4m98mPS4uoE0CKaQqNoA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      dnXgTObzR1Or_0SOZnhe6Q: {
        id: 'dnXgTObzR1Or_0SOZnhe6Q',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/owl_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'D0D_rXJqSSq3ZO3iuQf9-Q': {
        id: 'D0D_rXJqSSq3ZO3iuQf9-Q',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      PMaYdbcOS3eQMWnlKWGfhg: {
        id: 'PMaYdbcOS3eQMWnlKWGfhg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      H_FZsM7AQd21oZnyqVU61g: {
        id: 'H_FZsM7AQd21oZnyqVU61g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      QbbJZaAgRICHPeboEEUUEw: {
        id: 'QbbJZaAgRICHPeboEEUUEw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      N9VRIcyBTZGd5q2v_gVoPQ: {
        id: 'N9VRIcyBTZGd5q2v_gVoPQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Lfc_ADOrQI-Vsed_BWELTg': {
        id: 'Lfc_ADOrQI-Vsed_BWELTg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'IwaBN5jqSpGCm-K9jPvFSQ': {
        id: 'IwaBN5jqSpGCm-K9jPvFSQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'BnMm_siVQ0-qkOvFHXPDQQ': {
        id: 'BnMm_siVQ0-qkOvFHXPDQQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/spotted_flycatcher_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      YjCSmN3lQCusLwWHs341CQ: {
        id: 'YjCSmN3lQCusLwWHs341CQ',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      N26WBNGrRbyn3vxWIUU0Kg: {
        id: 'N26WBNGrRbyn3vxWIUU0Kg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GzqalkjETry92NlZBFPctw: {
        id: 'GzqalkjETry92NlZBFPctw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      dwg2PrUnQ0KJNUz_FNQCGw: {
        id: 'dwg2PrUnQ0KJNUz_FNQCGw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      c5T0xDW5STeSoZl6m_Cpsg: {
        id: 'c5T0xDW5STeSoZl6m_Cpsg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'WvmKTjm2Tc-hLg3PIJmQTg': {
        id: 'WvmKTjm2Tc-hLg3PIJmQTg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      KCUdtt2ATXqKUpbuu9IZ_g: {
        id: 'KCUdtt2ATXqKUpbuu9IZ_g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      Bf4YplqkQdyT2tjOpNVr3A: {
        id: 'Bf4YplqkQdyT2tjOpNVr3A',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/white_wagtail_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'IDcBa3EpSeG-vEoCHsElew': {
        id: 'IDcBa3EpSeG-vEoCHsElew',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      FdI_Wo9aSKCpcrrMjlccDg: {
        id: 'FdI_Wo9aSKCpcrrMjlccDg',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      AN7s8X7QRumirmOg9BIrFA: {
        id: 'AN7s8X7QRumirmOg9BIrFA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      JwNl5LvXTGSJdn4fWZ87qw: {
        id: 'JwNl5LvXTGSJdn4fWZ87qw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      OYZ74KypQf6vdwJkfJVHJw: {
        id: 'OYZ74KypQf6vdwJkfJVHJw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'D9_DzbJaReedKu65hF5O-Q': {
        id: 'D9_DzbJaReedKu65hF5O-Q',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      QBfBDBlhSIWpR9S9aOaB2A: {
        id: 'QBfBDBlhSIWpR9S9aOaB2A',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      NFMDLBAkRYehf9hYr0tGRA: {
        id: 'NFMDLBAkRYehf9hYr0tGRA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/vulture_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      H62rW6l4RBatauCDM4davA: {
        id: 'H62rW6l4RBatauCDM4davA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_1.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      S6Rg1ZXcSxO8kBttAYjsXw: {
        id: 'S6Rg1ZXcSxO8kBttAYjsXw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_2.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GeCwYVGxTECvVVY5cpNRWA: {
        id: 'GeCwYVGxTECvVVY5cpNRWA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_3.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'Q38sspcoQGauLP7wqT-aSw': {
        id: 'Q38sspcoQGauLP7wqT-aSw',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_4.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      'M473Pf4ST_aAyFS-5PyIrA': {
        id: 'M473Pf4ST_aAyFS-5PyIrA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_5.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GIXmGJhsScWODxq9bMnU8g: {
        id: 'GIXmGJhsScWODxq9bMnU8g',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_6.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      J4iK1_hjTl67ADuMNS9L1A: {
        id: 'J4iK1_hjTl67ADuMNS9L1A',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_7.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      PVmg2nIgScq7LU6w4xNUUA: {
        id: 'PVmg2nIgScq7LU6w4xNUUA',
        deckId: 'J9G3J2fcS_Kr0hI2nPj9oA',
        width: 532,
        height: 820,
        type: 'card',
        faceDown: false,
        image: 'games/aviary/woodpecker_8.png',
        x: 50,
        y: 50,
        rotation: 0,
        counts: '1',
        layer: 3,
      },
      GTAFlzH6SOW3hasFXajJ0A: {
        id: 'GTAFlzH6SOW3hasFXajJ0A',
        type: 'player',
        name: 'player',
        width: 261.904296875,
        height: 32,
        color: '#2ecc71',
        x: 46.968834713516344,
        y: -719.9159827668233,
        rotation: 0,
        layer: 9,
      },
      'C2a4BNPKRjGrUV6h-Lyrsw': {
        id: 'C2a4BNPKRjGrUV6h-Lyrsw',
        type: 'player',
        name: 'player',
        width: 261.904296875,
        height: 32,
        color: '#2ecc71',
        x: 34.8441735675824,
        y: -598.669371307481,
        rotation: 0,
        layer: 9,
      },
      'D2fM8-VDSHKScA7ci00Icg': {
        id: 'D2fM8-VDSHKScA7ci00Icg',
        type: 'player',
        name: 'player',
        width: 261.904296875,
        height: 32,
        color: '#3498db',
        x: 944.1937595126492,
        y: -583.5135448750633,
        rotation: 0,
        layer: 9,
      },
    },
  },
};
