import { EditorState } from '../types';

export const Cards: EditorState = {
  version: 1,
  store: 'included',
  id: 'cards',
  disableSync: true,
  name: 'Playing Cards',
  description: `
  There are 57,939 card games, over 9 of which are playable on Earth!
  `,
  curScenario: 'Ea_H6ATdRlOTq-7HcFK9Yg',
  scenarios: {
    'Ea_H6ATdRlOTq-7HcFK9Yg': {
      id: 'Ea_H6ATdRlOTq-7HcFK9Yg',
      name: 'Scenario 1',
      pieces: [
        'ADFQSHEUS_6G0arGqck9oQ',
        'f0waVKWJT-uT-9g9cXII1w',
        'd1Ls-WXBR9K8YtNJZiuhbw',
        'fMAnActcRgStUQdzwuux9g',
        'aTYKWmuNSqyOQrs7RpIfNQ',
        'YHkAYGgeRf2py2834JxLHA',
        'aRvjIkslSK6FtNwJwH2IaA',
        'DHS2djdxSL60zoOBMVN2mw',
        'U4lye1zFSgie54-3rSsQ_w',
        'LG5KxY3WSaWeUwKQsZpKJA',
        'XziDjlmhQQamcMpQdHVQ6Q',
        'TtXy0wgSTWu_URU5vZMtuQ',
        'S5FP-gETRhmCiMu15vunIQ',
        'Hfipe6IXStyDPjBoxICLow',
        'YeSSVar3RhahcXboEEdxKw',
        'Bw5fCpQZSTiKx2oZEw4Zbw',
        'I3FIGh39QASc8KC-XYG01w',
        'LvjakCXZQJKM51-n2w5g6g',
        'XbVRY9-RSNOJkPLIfHIk9g',
        'DPc7mriTQjOjLq2dLwzWng',
        'Z-FIyswLRkiJexUlZpypZA',
        'KsIikXcnRu-ZY5OpGYTZPQ',
        'QHqxDr0tTg6fp3TBmQYr6g',
        'eohzhivIRfCSh49Yt8secA',
        'XoubQ8wdQKGwgDbJ-dt0yg',
        'R6ecpyYHTfuZfzTp2emHYA',
        'cMzZjFH1QSOP2DxZdYmDfA',
        'XLNiIl0eRSqSALu1F1cpIQ',
        'fydUE7AAQ8OKb3IcAn2ybQ',
        'LCCpHNcpRU2DT6LWyGnIkw',
        'ETqr3Eh-SBWTIkJsAH111w',
        'LmMEXf35SyKMQpTQjs2E4A',
        'chBsl1sjQ0qCY498sBU90g',
        'IiCxdBn1TLSB7J4VzcnZhQ',
        'R1SGiLP2RFGiyKwZDv-GWw',
        'RujdlIO0RSuhzZdIWbflpA',
        'XfxBbWYQTs6IXcO7_zvr1g',
        'cS3KRnh1QUurujzWFNUCNQ',
        'ZoXDnx1ARf6I3SghJYDxKw',
        'O3G5Jd87TSa0pyQMN_r9Lw',
        'DMozJf8zScalyPPmynnKpg',
        'MBFCt-jXQvawJupiA8Dr1A',
        'ZwODulcqQPC47omIj-2dsQ',
        'fc_nhX15SyGur-EtH9CRsw',
        'OQVB-Q8lTtuQxQ59vkq6XQ',
        'YiiUepHdTHSO8tXNRj_TXA',
        'G2HMw7R5SqKxshNcK4FCWQ',
        'Mtrw9oxJRvaYjmQqUEVoCw',
        'VUxXY-LnT4KJGNqObbSEyQ',
        'Hb_6qPSAQeKmDYlzh0P_Hw',
        'P-o9GIRvQWSTmHyUUMTBUA',
        'bjR7WWQuRWig0Thdlb3oiw',
        'dMHHVHSuQw2VubLh5PCEYA',
        'IkNopk-NRsyudqW0Dyvtlw',
        'adUGR6JcSFW9lBm_2W68HA',
        'bJX-OScyR32wcqiFne6YwQ',
        'T3ckrjAXTQaNj3xTrS093g',
        'Rzh6-Il6SxqadqnV316SPw',
        'PyOEyegPQii2faY8d8LsQw',
      ],
      players: [
        'ADFQSHEUS_6G0arGqck9oQ',
        'f0waVKWJT-uT-9g9cXII1w',
        'bJX-OScyR32wcqiFne6YwQ',
        'T3ckrjAXTQaNj3xTrS093g',
        'Rzh6-Il6SxqadqnV316SPw',
        'PyOEyegPQii2faY8d8LsQw',
      ],
    },
  },
  pieces: {
    ADFQSHEUS_6G0arGqck9oQ: {
      id: 'ADFQSHEUS_6G0arGqck9oQ',
      type: 'player',
      name: 'Player',
      x: 15.049728337952274,
      y: -424.60941761765645,
      width: 261.904296875,
      height: 32,
      color: '#e74c3c',
      rotation: 0,
      layer: 99,
    },
    'f0waVKWJT-uT-9g9cXII1w': {
      id: 'f0waVKWJT-uT-9g9cXII1w',
      type: 'player',
      name: 'Player',
      x: 734.5346614589012,
      y: -423.60941761765633,
      width: 261.904296875,
      height: 32,
      color: '#f1c40f',
      rotation: 0,
      layer: 99,
    },
    'd1Ls-WXBR9K8YtNJZiuhbw': {
      id: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 233.54931058620556,
      height: 356.91472066430254,
      type: 'deck',
      layer: 3,
      cards: [],
      name: 'Deck',
      image: 'games/cards/purple_back.png',
      x: 71.56011050756331,
      y: 67.75538512387567,
      rotation: 0,
    },
    fMAnActcRgStUQdzwuux9g: {
      id: 'fMAnActcRgStUQdzwuux9g',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/2C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    aTYKWmuNSqyOQrs7RpIfNQ: {
      id: 'aTYKWmuNSqyOQrs7RpIfNQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/2D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    YHkAYGgeRf2py2834JxLHA: {
      id: 'YHkAYGgeRf2py2834JxLHA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/2H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    aRvjIkslSK6FtNwJwH2IaA: {
      id: 'aRvjIkslSK6FtNwJwH2IaA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/2S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    DHS2djdxSL60zoOBMVN2mw: {
      id: 'DHS2djdxSL60zoOBMVN2mw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/3C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'U4lye1zFSgie54-3rSsQ_w': {
      id: 'U4lye1zFSgie54-3rSsQ_w',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/3D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    LG5KxY3WSaWeUwKQsZpKJA: {
      id: 'LG5KxY3WSaWeUwKQsZpKJA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/3H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    XziDjlmhQQamcMpQdHVQ6Q: {
      id: 'XziDjlmhQQamcMpQdHVQ6Q',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/3S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    TtXy0wgSTWu_URU5vZMtuQ: {
      id: 'TtXy0wgSTWu_URU5vZMtuQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/4C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'S5FP-gETRhmCiMu15vunIQ': {
      id: 'S5FP-gETRhmCiMu15vunIQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/4D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    Hfipe6IXStyDPjBoxICLow: {
      id: 'Hfipe6IXStyDPjBoxICLow',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/4H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    YeSSVar3RhahcXboEEdxKw: {
      id: 'YeSSVar3RhahcXboEEdxKw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/4S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    Bw5fCpQZSTiKx2oZEw4Zbw: {
      id: 'Bw5fCpQZSTiKx2oZEw4Zbw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/5C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'I3FIGh39QASc8KC-XYG01w': {
      id: 'I3FIGh39QASc8KC-XYG01w',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/5D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'LvjakCXZQJKM51-n2w5g6g': {
      id: 'LvjakCXZQJKM51-n2w5g6g',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/5H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'XbVRY9-RSNOJkPLIfHIk9g': {
      id: 'XbVRY9-RSNOJkPLIfHIk9g',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/5S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    DPc7mriTQjOjLq2dLwzWng: {
      id: 'DPc7mriTQjOjLq2dLwzWng',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 683,
      height: 1052,
      type: 'card',
      image: 'games/cards/6C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'Z-FIyswLRkiJexUlZpypZA': {
      id: 'Z-FIyswLRkiJexUlZpypZA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/6D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'KsIikXcnRu-ZY5OpGYTZPQ': {
      id: 'KsIikXcnRu-ZY5OpGYTZPQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/6H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    QHqxDr0tTg6fp3TBmQYr6g: {
      id: 'QHqxDr0tTg6fp3TBmQYr6g',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 683,
      height: 1052,
      type: 'card',
      image: 'games/cards/6S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    eohzhivIRfCSh49Yt8secA: {
      id: 'eohzhivIRfCSh49Yt8secA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/7C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'XoubQ8wdQKGwgDbJ-dt0yg': {
      id: 'XoubQ8wdQKGwgDbJ-dt0yg',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 683,
      height: 1052,
      type: 'card',
      image: 'games/cards/7D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    R6ecpyYHTfuZfzTp2emHYA: {
      id: 'R6ecpyYHTfuZfzTp2emHYA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/7H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    cMzZjFH1QSOP2DxZdYmDfA: {
      id: 'cMzZjFH1QSOP2DxZdYmDfA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/7S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    XLNiIl0eRSqSALu1F1cpIQ: {
      id: 'XLNiIl0eRSqSALu1F1cpIQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/8C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    fydUE7AAQ8OKb3IcAn2ybQ: {
      id: 'fydUE7AAQ8OKb3IcAn2ybQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/8D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    LCCpHNcpRU2DT6LWyGnIkw: {
      id: 'LCCpHNcpRU2DT6LWyGnIkw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/8H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'ETqr3Eh-SBWTIkJsAH111w': {
      id: 'ETqr3Eh-SBWTIkJsAH111w',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/8S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    LmMEXf35SyKMQpTQjs2E4A: {
      id: 'LmMEXf35SyKMQpTQjs2E4A',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/9C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    chBsl1sjQ0qCY498sBU90g: {
      id: 'chBsl1sjQ0qCY498sBU90g',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/9D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    IiCxdBn1TLSB7J4VzcnZhQ: {
      id: 'IiCxdBn1TLSB7J4VzcnZhQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/9H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'R1SGiLP2RFGiyKwZDv-GWw': {
      id: 'R1SGiLP2RFGiyKwZDv-GWw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/9S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    RujdlIO0RSuhzZdIWbflpA: {
      id: 'RujdlIO0RSuhzZdIWbflpA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/10C.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    XfxBbWYQTs6IXcO7_zvr1g: {
      id: 'XfxBbWYQTs6IXcO7_zvr1g',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/10D.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    cS3KRnh1QUurujzWFNUCNQ: {
      id: 'cS3KRnh1QUurujzWFNUCNQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/10H.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    ZoXDnx1ARf6I3SghJYDxKw: {
      id: 'ZoXDnx1ARf6I3SghJYDxKw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/10S.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    O3G5Jd87TSa0pyQMN_r9Lw: {
      id: 'O3G5Jd87TSa0pyQMN_r9Lw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/AC.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    DMozJf8zScalyPPmynnKpg: {
      id: 'DMozJf8zScalyPPmynnKpg',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/AD.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'MBFCt-jXQvawJupiA8Dr1A': {
      id: 'MBFCt-jXQvawJupiA8Dr1A',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/AH.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'ZwODulcqQPC47omIj-2dsQ': {
      id: 'ZwODulcqQPC47omIj-2dsQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/AS.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'fc_nhX15SyGur-EtH9CRsw': {
      id: 'fc_nhX15SyGur-EtH9CRsw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/JC.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'OQVB-Q8lTtuQxQ59vkq6XQ': {
      id: 'OQVB-Q8lTtuQxQ59vkq6XQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/JD.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    YiiUepHdTHSO8tXNRj_TXA: {
      id: 'YiiUepHdTHSO8tXNRj_TXA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/JH.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    G2HMw7R5SqKxshNcK4FCWQ: {
      id: 'G2HMw7R5SqKxshNcK4FCWQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/JS.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    Mtrw9oxJRvaYjmQqUEVoCw: {
      id: 'Mtrw9oxJRvaYjmQqUEVoCw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/KC.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'VUxXY-LnT4KJGNqObbSEyQ': {
      id: 'VUxXY-LnT4KJGNqObbSEyQ',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/KD.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    Hb_6qPSAQeKmDYlzh0P_Hw: {
      id: 'Hb_6qPSAQeKmDYlzh0P_Hw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 683,
      height: 1052,
      type: 'card',
      image: 'games/cards/KH.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'P-o9GIRvQWSTmHyUUMTBUA': {
      id: 'P-o9GIRvQWSTmHyUUMTBUA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/KS.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    bjR7WWQuRWig0Thdlb3oiw: {
      id: 'bjR7WWQuRWig0Thdlb3oiw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/QC.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    dMHHVHSuQw2VubLh5PCEYA: {
      id: 'dMHHVHSuQw2VubLh5PCEYA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/QD.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'IkNopk-NRsyudqW0Dyvtlw': {
      id: 'IkNopk-NRsyudqW0Dyvtlw',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/QH.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    adUGR6JcSFW9lBm_2W68HA: {
      id: 'adUGR6JcSFW9lBm_2W68HA',
      deckId: 'd1Ls-WXBR9K8YtNJZiuhbw',
      width: 691,
      height: 1056,
      type: 'card',
      image: 'games/cards/QS.png',
      x: 50,
      y: 50,
      faceDown: false,
      rotation: 0,
      counts: '1',
      layer: 3,
    },
    'bJX-OScyR32wcqiFne6YwQ': {
      id: 'bJX-OScyR32wcqiFne6YwQ',
      type: 'player',
      name: 'player',
      width: 261.904296875,
      height: 32,
      color: '#2ecc71',
      x: 1433.1796460756168,
      y: -409.9876497414258,
      rotation: 0,
      layer: 9,
    },
    T3ckrjAXTQaNj3xTrS093g: {
      id: 'T3ckrjAXTQaNj3xTrS093g',
      type: 'player',
      name: 'player',
      width: 261.904296875,
      height: 32,
      color: '#3498db',
      x: 1410.6627681162447,
      y: 596.8384647275695,
      rotation: 0,
      layer: 9,
    },
    'Rzh6-Il6SxqadqnV316SPw': {
      id: 'Rzh6-Il6SxqadqnV316SPw',
      type: 'player',
      name: 'player',
      width: 261.904296875,
      height: 32,
      color: '#9b59b6',
      x: 622.5720395382789,
      y: 596.8384647275695,
      rotation: 0,
      layer: 9,
    },
    PyOEyegPQii2faY8d8LsQw: {
      id: 'PyOEyegPQii2faY8d8LsQw',
      type: 'player',
      name: 'player',
      width: 261.904296875,
      height: 32,
      color: '#34495e',
      x: 4.966244081260129,
      y: 600.0551615789082,
      rotation: 0,
      layer: 9,
    },
  },
};
